[project]
name = "ticket-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg==0.29.0",
    "celery[redis]==5.4.0",
    "fastapi==0.111.0",
    "httpx==0.28.0",
    "langchain>=0.3.25",
    "langchain-core>=0.3.58",
    "langchain-groq>=0.2.4",
    "langgraph>=0.2.60",
    "passlib[argon2]==1.7.4",
    "pydantic==2.7.4",
    "pydantic-settings==2.2.1",
    "python-dotenv==1.0.1",
    "python-jose[cryptography]==3.3.0",
    "python-multipart==0.0.9",
    "sqlalchemy[asyncio]==2.0.30",
    "structlog==24.4.0",
    "uvicorn[standard]==0.29.0",
]
